#!/bin/dash

if [ ! -d ".pig" ]
then 
    echo "pigs-branch: error: pigs repository directory .pig not found" >&2
    exit 1
fi 

cd .pig || exit 1

list_branches=false
# create_branch=false
delete_branch=false

if [ $# -eq 0 ]
then 
    list_branches=true
fi

if [ $# -eq 1 ]
then 
    if [ "$1" = "-d" ]
    then 
        echo "pigs-branch: error: branch name required" >&2
        exit 1
    elif [ "$1" = "master" ]
    then 
        # need to also work for ones that arent master
        echo "pigs-branch: error: branch 'master' already exists" >&2
        exit 1
    else 
        create_branch=true
    fi
fi

if [ $# -eq 2 ]
then 
    if [ "$2" = "master" ]
    then 
        echo "pigs-branch: error: can not delete branch 'master': default branch" >&2
        exit 1
    else 
    delete_branch=true
    fi
fi

i=0
backup_directory='.snapshot.'
if [ ! -d "$backup_directory$i" ]
then 
    echo "pigs-branch: error: this command can not be run until after the first commit" >&2
    exit 1
fi

if [ $# -eq 0 ]
then 
    if [ ! -d "branches" ] 
    then 
        echo "master"
        exit
    fi 

    cd branches || exit 1
    
    for branch in *
    do 
        echo "$branch"
    done 
elif [ $# -eq 1 ]
then 
    branch_name=$1
    if [ -d "branches" ]
    then 
        cd branches || exit 1
        if [ -d "$branch_name" ]
        then 
            echo "pigs-branch: error: branch '$branch_name' already exists" >&2
            exit 1
        else 
            mkdir "$branch_name"
            # copy files to branch
        fi 
    else 
        mkdir branches
        cd branches || exit 
        mkdir master
        mkdir "$branch_name"
        # copy files to branch
    fi 
elif [ $# -eq 2 ]
then 
    branch_name=$2
    if [ -d "branches" ]
    then 
        cd branches || exit 1
        if [ -d "$branch_name" ]
        then 
            rm -r "$branch_name"
            echo "Deleted branch '$branch_name'"
        else 
            echo "pigs-branch: error: branch '$branch_name' doesn't exist" >&2
        fi 
    else 
        echo "pigs-branch: error: branch '$branch_name' doesn't exist" >&2
    fi
fi 




